theme = "solarized_dark"

[editor]
line-number = "relative"
mouse = true
color-modes = true

[editor.cursor-shape]
insert = "underline"
normal = "block"
select = "hidden"

[editor.file-picker]
hidden = false
[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "all"
[editor.soft-wrap]
enable = true

[editor.whitespace.characters]
tab = "→"
newline = "⏎"
tabpad = "·"
[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1
